-- AlterTable
ALTER TABLE "reports" ADD COLUMN     "dashboard_abs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dashboard_abs_comment" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "dashboard_airbag" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dashboard_airbag_comment" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "dashboard_battery" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dashboard_battery_comment" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "dashboard_check_engine" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dashboard_check_engine_comment" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "dashboard_esp" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dashboard_esp_comment" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "dashboard_oil_pressure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dashboard_oil_pressure_comment" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "dashboard_tire_pressure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dashboard_tire_pressure_comment" TEXT NOT NULL DEFAULT '';
