###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine As development

USER node

WORKDIR /proj

COPY --chown=node:node . .

RUN npm ci

###################
# BUILD FOR PRODUCTION
###################

FROM development As build

WORKDIR /proj

RUN npm run build:uploader

ENV NODE_ENV=production

RUN npm ci --omit=dev && npm cache clean --force

###################
# PRODUCTION
###################

FROM node:18-alpine As production

COPY --chown=node:node --from=build /proj/node_modules ./node_modules
COPY --chown=node:node --from=build /proj/dist/apps/uploader ./dist/apps/uploader

CMD [ "node", "/dist/apps/uploader/main.js" ]